### PR TITLE
[#213] test public API open_or_create_with_attributes

### PR DESCRIPTION
**Pull request by xieyuschen**
## Notes for Reviewer
* Public API `open_or_create_with_attributes` should be tested.
* update the doc of open_or_create_with_attributes.

## Pre-Review Checklist for the PR Author

1. [X] Add sensible notes for the reviewer
1. [X] PR title is short, expressive and meaningful
1. [X] Relevant issues are linked in the [References](#references) section
1. [X] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [X] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [X] Commits messages are according to this [guideline][commit-guidelines]
    - [X] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [X] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [X] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Relates to #213

### CODE REVIEW

**Comment by elfenpiff** [comment]
@xieyuschen you forget to add the Relates to #213 at the end of the PR description - I added it for you!

**Review by elfenpiff — APPROVED** [review]
Thank you very much for your contribution. As soon as the CI is green we merge it.

**Comment by xieyuschen** [comment]
> Thank you very much for your contribution. As soon as the CI is green we merge it. I think you need to format the code.

my bad, I have forgot to add the `fmt` into my git hooks. i have amended the commit and pushed it. thanks a lot.

**Comment by xieyuschen** [comment]
@elfenpiff , could you kindly help to re-run the failed pipeline? Only windows failed and irrelevant to the current PR. I don't have permission to re-run the failure ci and trigger the whole pipeline takes more time.

```
--- STDOUT:              iceoryx2-bb-threadsafe::trigger_queue_tests trigger_queue_one_pop_notifies_exactly_one_timed_push ---

running 1 test
test trigger_queue_one_pop_notifies_exactly_one_timed_push ... FAILED

failures:

failures:
    trigger_queue_one_pop_notifies_exactly_one_timed_push

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 11 filtered out; finished in 0.20s


--- STDERR:              iceoryx2-bb-threadsafe::trigger_queue_tests trigger_queue_one_pop_notifies_exactly_one_timed_push ---
thread '<unnamed>' panicked at iceoryx2-bb\threadsafe\tests\trigger_queue_tests.rs:267:17:
assertion failed: expr: sut.timed_push(0, TIMEOUT * 1000) == true;  value: false == true
stack backtrace:
```

**Review by elfenpiff — APPROVED** [review]

**Comment by elfenpiff** [comment]
> could you kindly help to re-run the failed pipeline?

@xieyuschen done. 

and its merge. Congratulations on your first of hopefully many contributions!

**Comment by xieyuschen** [comment]
> > could you kindly help to re-run the failed pipeline?
> 
> 
> 
> @xieyuschen done. 
> 
> 
> 
> and its merge. Congratulations on your first of hopefully many contributions!

Cool, it's an interesting project and actually it's helpful to eliminate massive ser/desel cpu resources inside company. I have thought it in golang before but haven't chosen this approach because of the challenges and the corresponding maintenance inside a company. This time in an open source project I believe I can participate more:)
Thanks for your patience to review.

**Comment by elBoberido** [comment]
@xieyuschen if you are interested in golang, there is #225. If you want, I think you could ask in the issue if help is wanted.

**Pull request merged**
