### PR TITLE
[#54] Rename char in types.rs to c_char.

### LINKED ISSUE #54: Rename `char` in platform to `c_char`
## (Code) Example Of Cumbersome API

The type alias `char` in `iceoryx2_pal/posix/src/$PLATFORM$/types.rs` is mapped to `core::ffi::c_char` and not `u8`, this may lead to mixing it up with the rust primitive type `char`. 

## Improvement Suggestion

To have a clear distinction, the type alias in `types.rs` shall be renamed to `c_char`

### PR DESCRIPTION
**Pull request by Shock-1**
- Changes propogated

## Notes for Reviewer
Look at errno.rs for the change in buffer type from char to c_char. Looks valid to me but that was the only involved change.

## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Use either 'Closes #123' or 'Relates to #123' to reference the corresponding issue.

Closes #54

### CODE REVIEW

**Comment by elfenpiff** [comment]
@Shock-1 awesome, thanks for the contribution! It looks like the preflight_check found some unformatted files, could you please call `cargo fmt --all -- --check` in the iceoryx2 root directory and format all files correctly. When this is done, I am happy to merge this PR.

**Comment by elfenpiff** [comment]
@Shock-1 ouh I realized that every file in `iceoryx2-pal/posix/src/$PLATFORM/*.rs` must now use `c_char` as input argument instead of `char`. This is why the platforms macos and freebsd are failing.

But I think a simple search and replace should fix it.

**Comment by elfenpiff** [comment]
@Shock-1 Ouh man, I should have known that platforms are always a little bit beastly when you tickle them.

Do you need a little bit of support here? I have all failing platforms running and could fix them on your branch.
I think in windows some files are still missing and for freebsd/macos we need some more `.cast()` to cast to the right pointer type.

**Comment by Shock-1** [comment]
Hmm, not having a machine with that OS is a bit blinding. I can at least test for Windows and then double-check.

**Comment by elBoberido** [comment]
@Shock-1 there are still some files which use the old `char` type alias. Just grep the code base for ` char` (there is a space before `char`) and there is a high chance it should be `posix::c_char`

**Comment by Shock-1** [comment]
Will get back to it tomorrow after work.  Thanks for all the help. Really looking forward to contributing more. Love to see more rust in my robotics.

**Comment by elfenpiff** [comment]
@Shock-1 I would like to create a release soon and would love to include your changes. Do you think you have time to finish this PR soon?

**Comment by Shock-1** [comment]
> @Shock-1 I would like to create a release soon and would love to include your changes. Do you think you have time to finish this PR soon?

Yeah working on it. Windows is done. Just doing double-checks for Macos.

**Comment by Shock-1** [comment]
@elfenpiff Take a look at it and merge it if it looks good.

**Review by elfenpiff — APPROVED** [review]

**Pull request merged**
